### ISSUE TITLE
Build error android

### ISSUE THREAD

**Issue by Saikatsaha1996** [BlueDragon747/Blakecoin#14]
![Screenshot_2022-06-02-21-32-31-181_com termux](https://user-images.githubusercontent.com/72664192/171674196-5b23ff78-cb10-41c1-a5fc-ccf91de963ed.jpg)

**Comment by BlueDragon747** [comment]
no support for any android versions in leveldb afaik try: 

chmod +x Blakecoin/src/leveldb/build_detect_platform
cd  Blakecoin/src/leveldb/
make libleveldb.a libmemenv.a
cd ..

but as you have other posix thread errors best to use a supported platform:

Windows: 7-11
Ubuntu: 16.04-20.04
MacOS: 10.11-10.16
